### ISSUE TITLE
PA Review: User Auth

### ISSUE THREAD

**Issue by zixlin7** [zixlin7/chefsTable#2]
- [x] users can sign up
- [x] users can log in
- [x] users can log out
- [x] errors are rendered upon unsuccessful log in and sign up
- [x] demo user functionality

**Comment by Vanchen07** [comment]
Thanks for creating the issue, can you update the bullets to include the following: 
- users can sign up
- users can log in
- users can log out
- errors are rendered upon unsuccessful log in and sign up
- demo user functionality

**Comment by zixlin7** [comment]
updated. Thanks Vanessa!

**Comment by Vanchen07** [comment]
Thanks for the update. All looks good, I will go ahead and close this issue.
